paths:
  /api/products/:
    get:
      sumary: Get all products
      tags:
        - Products
      responses:
        200:
          description: productos cargados exitosamente
        500:
          description: error al cargar productos, generado por una query defectuosa
  /api/products/:code:
    get:
      sumary: Get product by code
      tags:
        - Products
      parameters:
        - in: path
          name: code
          required: true
          description: codigo del producto

      responses:
        200:
          description: producto cargado exitosamente
        404:
          description: producto no encontrado
        500:
          description: error al cargar producto, generado por una query defectuosa
  /api/products/addnewProduct:
    post:
      sumary: Create a new product
      tags:
        - Products
      requestBody:
        content:

      responses:
        200:
          description: producto creado exitosamente
        500:
          description: error al crear producto, generado por una query defectuosa

  /api/products/{code}:
    put:
      sumary: Update product by code
      tags:
        - Products
      parameters:
        - in: path
          name: code
          required: true
          description: codigo del producto
      requestBody:
        content:

      responses:
        200:
          description: producto actualizado exitosamente
        404:
          description: producto no encontrado
        500:
          description: error al actualizar producto, generado por una query defectuosa
  /api/products/:pcode:
    delete:
      sumary: Delete product by code
      tags:
        - Products
      parameters:
        - in: path
          name: pcode
          required: true
          description: codigo del producto
      responses:
        200:
          description: producto eliminado exitosamente
        404:
          description: producto no encontrado
        500:
          description: error al eliminar producto, generado por una query defectuosa
components:
  schemas:
    Products:
      properties:
        title:
          type: String
          description: titulo del producto
        description:
         type: String
        description: descripcion del producto
       code:
         type: Number
         description: codigo del producto
       price:
         type: Number
         description: precio del producto
       stock:
         type: Number
         description: stock del producto
       category:
        type: String
         description: categoria del producto
        thumbnail:
         type: String
         description: imagen del producto