paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      tags:
        - Productos
      responses:
        200:
          description: Productos cargados exitosamente
        500:
          description: Error al cargar productos, generado por una consulta defectuosa
  /api/products/:code:
    get:
      summary: Obtener producto por código
      tags:
        - Productos
      parameters:
        - in: path
          name: code
          required: true
          description: Código del producto
      responses:
        200:
          description: Producto cargado exitosamente
        404:
          description: Producto no encontrado
        500:
          description: Error al cargar producto, generado por una consulta defectuosa
  /api/products/addnewProduct:
    post:
      summary: Crear un nuevo producto
      tags:
        - Productos
      requestBody:
        content:
          application/json: {}
      responses:
        200:
          description: Producto creado exitosamente
        500:
          description: Error al crear producto, generado por una consulta defectuosa
  /api/products/{code}:
    put:
      summary: Actualizar producto por código
      tags:
        - Productos
      parameters:
        - in: path
          name: code
          required: true
          description: Código del producto
      requestBody:
        content:
          application/json: {}
      responses:
        200:
          description: Producto actualizado exitosamente
        404:
          description: Producto no encontrado
        500:
          description: Error al actualizar producto, generado por una consulta defectuosa
  /api/products/{pcode}:
    delete:
      summary: Eliminar producto por código
      tags:
        - Productos
      parameters:
        - in: path
          name: pcode
          required: true
          description: Código del producto
      responses:
        200:
          description: Producto eliminado exitosamente
        404:
          description: Producto no encontrado
        500:
          description: Error al eliminar producto, generado por una consulta defectuosa

components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: string
          description: ID del producto
        category:
          type: string
          description: Categoría del producto
        title:
          type: string
          description: Nombre del producto
        modelo:
          type: string
          description: Modelo del producto
        description:
          type: string
          description: Características del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
        code:
          type: string
          description: Código del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: number
          description: stock del producto
      required:
        - category
        - title
        - code
        - price
        - stock
      example:
        category: "Guitarras Electricas"
        title: "Gibson Les Paul R9"
        description: "Reedision de la mitica Gibson Les Paul de 1959 a cargo del luthier y su equipo Custom Shop, Murphy Lab."
        code: "12"
        price: 12000
